### PR TITLE
build(deps): upgrade eslint-config-airbnb-typescript and @typescript-eslint/* packages to latest

### PR DESCRIPTION
**Pull request by davilima6**
Addresses .

## Purpose

This PR upgrades a couple of linter-related libraries to facilitate the upgrade of Typescript to latest in consuming projects

Currently, using TS >= 5.4.0 results in a linter warning similar to this (incl. in this very repo):

```
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.
You may find that it works just fine, or you may not.
SUPPORTED TYPESCRIPT VERSIONS: >=4.3.5 <5.4.0
YOUR TYPESCRIPT VERSION: 5.4.5
Please only submit bug reports when using the officially supported version.
```

## Approach and changes

- [x] upgraded `eslint-config-airbnb-typescript` to latest `^18.0.0`
- [x] upgraded `@typescript-eslint/{estlint-plugin,parser}` to latest `^7.5.0` (maybe this needs to be instead `^6.22.0 || ^7.5.0`? 🤔), fixing the error above

## Definition of done

- [ ] Development completed
- [ ] Reviewers assigned
- [ ] Unit and integration tests

### CODE REVIEW

**Comment by hilleer** [comment]
This would be super useful bump! 🙌

**Comment by davilima6** [comment]
I'm currently failing to sign the CLA to unblock this PR (the [page](https://opensource.sumup.com/cla) doesn't seem to work). Needs actual testing too, and a changelog entry. Hopefully I'll have time to move on with it this week or by the beginning of the next one. In the meantime, if anyone want to move it forward just let me know.

**Comment by connor-baer** [comment]
@davilima6 You don't need to sign the CLA since you're employed by SumUp. 

The CLA bot has been broken for a while 😞  I'll make a PR to remove the requirement and discourage external contributions.

**Comment by connor-baer** [comment]
This will have to be released as a breaking change since `typescript-eslint` v7 raised the minimum Node version requirement to v18.18+ in line with ESLint v9 (https://github.com/typescript-eslint/typescript-eslint/pull/8377). Foundry currently requires v18.12+.

**Comment by davilima6** [comment]
@connor-baer , thanks for having a look. Your merge commit has cleared the check failure.

I don't think there's a rush to release this, so we could batch with other breaking changes. Are there any others in sight?

**Comment by connor-baer** [comment]
@davilima6 [ESLint v9](https://eslint.org/blog/2024/04/eslint-v9.0.0-released/) was released a month ago and I was hoping to upgrade to it soon. However, a lot of the plugins we use aren't compatible yet, so I'm open to releasing a major version sooner.

**Comment by davilima6** [comment]
@connor-baer, got it. Since this breaking change shouldn't be a too hard issue for users (afaik), I bumped the versions to latest and added a changeset, so feel also free to edit it directly, as well as release whenever you think it's best. If you need any other adjustments, just let me know. I'll try to test later in our project using Yalc.

**Review by connor-baer — APPROVED** [review]
Thank you!

**Pull request merged**
